### ISSUE TITLE
FormatException: Unexpected character (at character 1)

### ISSUE THREAD

**Issue by elianfish** [huiyiqun/pub-mirror#8]
use   huiyiqun/pub_mirror:v1.0.7   -u https://pub.flutter-io.cn/packages

Unhandled exception:
FormatException: Unexpected character (at character 1)
<!DOCTYPE html>
^

#0      _ChunkedJsonParser.fail (dart:convert/runtime/libconvert_patch.dart:1357:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert/runtime/libconvert_patch.dart:1253:9)
#2      _ChunkedJsonParser.parse (dart:convert/runtime/libconvert_patch.dart:921:22)
#3      _parseJson (dart:convert/runtime/libconvert_patch.dart:29:10)
#4      JsonDecoder.convert (dart:convert/json.dart:491:36)
#5      JsonCodec.decode (dart:convert/json.dart:149:41)
#6      PubClient.getPageOfPackages (package:pub_client/pub_client.dart:59:36)
<asynchronous suspension>
#7      PubMirrorTool.listAllPackages (package:pub_mirror/pub_mirror.dart:69:45)
<asynchronous suspension>
#8      PubMirrorTool.download (package:pub_mirror/pub_mirror.dart:158:31)
#9      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#10     PubMirrorTool.download (package:pub_mirror/pub_mirror.dart:150:18)
#11     main (file:///root/.pub-cache/hosted/pub.dartlang.org/pub_mirror-1.0.7/bin/pub_mirror.dart:46:8)
#12     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#13     main (file:///root/.pub-cache/hosted/pub.dartlang.org/pub_mirror-1.0.7/bin/pub_mirror.dart:39:5)
#14     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

**Comment by elianfish** [comment]
使用的源不对，忽略
